apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bigatao
  name: bigatao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigatao
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bigatao
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
